### ISSUE TITLE
Reduce API calls from watch command

### ISSUE THREAD

**Issue by FUTC-Coding** [Tanonic/CMCCLI#5]
At the moment the watch command calls GetCoinData() for every currency in the list seperatly. The api supports calling multiple currencies at the same time.
Example:
`/cryptocurrency/quotes/latest?symbol=,BTC,ETH`
Watch should call all currencies at the same time to reduce API calls.

**Comment by kloenk** [comment]
Maybe do This as an array parameter for GetCoindData()?
